id: P006666
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:14:32.988973
source_metadata:
  id: bdr:W29641
  title: གནས་མཆོག་ས་སྐྱ
  author: ''
  volumes:
    e46c1eb1c6d64ed09e6cc80f922397ab:
      image_group_id: I1PD28054
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
